### ISSUE TITLE
Help - Error when starting up the plugin

### ISSUE THREAD

**Issue by NusryNizam** [penpot/plugin-examples#1]
It says there's no `getTheme()` for some reason.
I'm using the react-starter-template, and no changes made to the starter project.

![image](https://github.com/user-attachments/assets/81537ccd-27c1-4df3-b44f-4a13d7e5e9fb)

**Comment by mavalroot** [comment]
Hello @NusryNizam !! Thank you for letting us know, we have updated the code so it should work now.
